from collections.abc import AsyncIterator, Sequence
from datetime import date, datetime
from decimal import Decimal
from typing import Protocol

from market_data.providers.capabilities import ProviderCapabilities
from market_data.providers.models import Candle, Instrument, Quote, Tick, Timeframe


class MarketDataProvider(Protocol):
    code: str
    capabilities: ProviderCapabilities
    async def get_intraday_candles(self, instrument: Instrument, as_of: datetime) -> list[Candle]: ...
    async def get_instruments(self) -> list[Instrument]: ...
    async def get_historical_candles(
        self, instrument: Instrument, timeframe: Timeframe, start: date, end: date, as_of: datetime
    ) -> list[Candle]: ...
    def subscribe_quotes(self, instruments: Sequence[Instrument]) -> AsyncIterator[Quote]: ...
    def subscribe_ticks(self, instruments: Sequence[Instrument]) -> AsyncIterator[Tick]: ...
    def subscribe_market_depth(self, instruments: Sequence[Instrument]) -> AsyncIterator[Quote]: ...
    async def unsubscribe(self, instrument_ids: Sequence[str]) -> None: ...
    async def get_quote(self, instrument: Instrument) -> Quote: ...
    async def get_ltp(self, instrument: Instrument) -> Decimal: ...
